### ISSUE TITLE
About embedding initialization

### ISSUE THREAD

**Issue by sijia1999** [layer6ai-labs/HGCF#3]
![捕获](https://user-images.githubusercontent.com/75306158/164628848-7a6b2322-4c9a-47b6-97f7-ee67076af825.PNG)
![捕获1](https://user-images.githubusercontent.com/75306158/164628875-804551b6-2038-4f63-adf9-29003e0676cd.PNG)
Hello author, I see that the embedding initialization in the code is not the same as that in the paper, the embedding in the code is not sampled from the Gaussian distribution, nor does it extend another dimension, so what is the situation~

**Comment by jianing-sun** [comment]
Hi sijia1999, thanks for your interest in our work. In the paper this is a very detailed explanation to make it easier to understand for readers. Implementation-wise, "extend to other dimension with zero" is done by masking out the first dimension which is equivalent to treating the first dimension as zero. In other words, we dont concatenate an extra dimension of zeros explicitly, instead the first dimension is considered as the extra dimension and treated as zeros. Please checkout the `expmap0` function, where this line https://github.com/layer6ai-labs/HGCF/blob/main/manifolds/hyperboloid.py#L84 specifically did that. The rest of the function after that line projected the parameters to the manifold. 

Regarding the distribution, since the parameters are initialized on tangent space not on the manifold directly (until the exponential mapping executed), it can be initialized under any common-used NN initialization, e.g. gaussian, uniform etc. In the paper we explained it with gaussian as an example to give high level ideas instead going to exact details, e.g. we also have a `scale` hyperparameter for the initialization distribution, to ease the understanding for readers.
